Modelo OSI
Open Systems Interconection > criado para facilitar a interconexao de sistemas de computadores
comunicação: faz uma ação > cod > mod > tx - leva para um modem que: rx > demod > decod ...
Usuário <> aplicação <> -rede- > <> linguagem <> gerenciamento de dados <> s.o. 
S.O. é unico que conversa com o hardware
modelo osi poossui 7 camadas
camada de transporte lida com a comunicação fim-a-fim
primitiva de serviço > comunicação entre as camadas
